name: Deploy to Oracle Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build --no-cache -f Dockerfile.development \
                    --build-arg NEXT_PUBLIC_GOOGLE_MAPS_API_KEY="${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}" \
                    --build-arg NEXT_PUBLIC_GOOGLE_MAPS_ID="${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_ID }}" \
                    --build-arg NEXT_PUBLIC_RAPIDAPI_KEY="${{ secrets.NEXT_PUBLIC_RAPIDAPI_KEY }}" \
                    --build-arg GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
                    --build-arg GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
                    --build-arg NEXTAUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}" \
                    -t ${{ secrets.DOCKER_USERNAME }}/travelingdog-dev-frontend:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/travelingdog-dev-frontend:latest

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Deploy to Azure VM
        run: |
          sshpass -p "${{ secrets.AZURE_SSH_PASS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_SSH_USER }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/travelingdog-dev-frontend:latest
          docker-compose down
          NEXT_PUBLIC_GOOGLE_MAPS_API_KEY="${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}" \
          NEXT_PUBLIC_GOOGLE_MAPS_ID="${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_ID }}" \
          NEXT_PUBLIC_RAPIDAPI_KEY="${{ secrets.NEXT_PUBLIC_RAPIDAPI_KEY }}" \
          GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
          GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
          NEXTAUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}" \
          docker-compose up -d
          EOF
